version: 2
jobs:
  build:
    branches:
      only:
        - /issues*/
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:11.3
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: taskapp_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-rails-demo-{{ checksum "Gemfile.lock" }}
            - v1-rails-demo

      - run: sudo apt install -y postgresql-client || true

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: v1-rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          command: |
            bundle exec rake db:create
            bundle exec rails db:migrate
            bundle exec rake db:seed
            bundle exec rake db:schema:load

      - run: bundle exec rubocop

      - run: bundle exec rspec
